### ISSUE TITLE
Visualize Attention Weights for a Decoder Only Model

### ISSUE THREAD

**Issue by aflah02** [inseq-team/inseq#208] opened 2023-07-28 17:02 UTC
## Question

How can I visualize the attention weights for a decoder only model like Pythia for a given input prompt?

## Additional context

I went over the tutorial [here](https://colab.research.google.com/github/inseq-team/inseq/blob/main/examples/inseq_tutorial.ipynb#scrollTo=UEdML7CrXRS7) which uses an Encoder-Decoder model and wanted to try this out for a Decoder only model

I tried to replace the model name only but it does not seem to work - 

```
model = inseq.load_model("EleutherAI/pythia-70m-deduped", "input_x_gradient")

out = model.attribute(
    input_texts="Hello everyone, hope you're enjoying the tutorial!",
    attribute_target=True,
    method="attention"
)
# out[0] is a shortcut for out.sequence_attributions[0]
out.sequence_attributions[0].source_attributions.shape
```

but I get the error - 

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-6df0e921faca>](https://localhost:8080/#) in <cell line: 11>()
      9 )
     10 # out[0] is a shortcut for out.sequence_attributions[0]
---> 11 out.sequence_attributions[0].source_attributions.shape

AttributeError: 'NoneType' object has no attribute 'shape'
```

However strangely I can still look at the outputs using -

```
out.sequence_attributions[0]._aggregator
out.show()
```

Is this the intended functioning?

Also I would love to get some help in interpreting the generated plot 

<img width="253" alt="image" src="https://github.com/inseq-team/inseq/assets/72096386/bd2265a0-5a24-431d-86d3-3f7ac059236f">

I'm confused about why are there some full rows and some rows with certain values masked and what exactly does a cell signify. I know this might be a trivial thing :(

## Checklist

- [x] I've searched the project's [`issues`](https://github.com/inseq-team/inseq/issues?q=is%3Aissue).

**Comment by gsarti** [comment] 2023-07-29 08:42
Hi @aflah02, thanks for reaching out!

For the encoder-decoder model used in the tutorial `input_texts` represent the input to the encoder, corresponding to the English sentence to be translated. On the contrary, for decoder-only models like Pythia, this input is the prompt from which the model should continue. In your example, the model is given a prompt `P = "Hello everyone, hope you're enjoying the tutorial!"` and generates `G = "\n\nI'm so happy to share this tutorial"`. We refer to `T = P + G` as the full target text.

Provided there is no source sequence but only a target to be continued in the case of decoder-only models, the `source_attributions` field of the out object is left empty (this is what causes the error you report). If you were to run `print(out.sequence_attributions[0].target_attributions.shape)` instead, it would print the shape of the attention matrix returned by the method, corresponding to `|T| x |G| x L x H`, where `|T|` is the full target length, `|G|` is the number of generated tokens, `L` is the number of model layers and `H` is the number of attention heads in the model.

Indeed, the plot you attached shows the expected behavior from the attribution output: the default aggregator of the attention outputs is used under the hood by `out.show` to mean-aggregate across the last two dimensions (heads and layers, in this order), producing the `|T| x |G| ` matrix you attached. A cell in row X and column Y in this matrix represents *the aggregated attention weight assigned to the model to prefix token X when generating token Y*, where aggregated attention corresponds in this case to the mean attention weight across all layers and heads. Leter in the tutorial you can find examples of how to use `aggregate` to perform custom aggregation to extract e.g. the weight of a single head in a single layer of the model.

Finally, the reason for missing values in the target matrix is that generation is a sequential process: when a new token (column) is being generated the model can attend only to previous tokens (rows) during prediction. After the token is generated, it gets added to the prefix (i.e. becomes the next row in the matrix) and can be used by the model to predict the next token, so it will have an attention score from here onwards. This produces an upper triangular pattern like the one you see in the image.

Hope it helps! :slightly_smiling_face: For further questions, it would be great if you wanted to join the Inseq Discord server! You can find the invite here: https://discord.gg/V5VgwwFPbu

**Closed by gsarti** 2023-07-29 08:42 UTC
Labels: question

**Comment by frankdarkluo** [comment] 2024-04-11 07:07
Hi, I have a quick question, how can we visualize the target attribution of a certain layer on a certain attention head? Is it possible the show code as an example, please?

**Comment by frankdarkluo** [comment] 2024-04-11 07:08
> Hi @aflah02, thanks for reaching out!
> 
> For the encoder-decoder model used in the tutorial `input_texts` represent the input to the encoder, corresponding to the English sentence to be translated. On the contrary, for decoder-only models like Pythia, this input is the prompt from which the model should continue. In your example, the model is given a prompt `P = "Hello everyone, hope you're enjoying the tutorial!"` and generates `G = "\n\nI'm so happy to share this tutorial"`. We refer to `T = P + G` as the full target text.
> 
> Provided there is no source sequence but only a target to be continued in the case of decoder-only models, the `source_attributions` field of the out object is left empty (this is what causes the error you report). If you were to run `print(out.sequence_attributions[0].target_attributions.shape)` instead, it would print the shape of the attention matrix returned by the method, corresponding to `|T| x |G| x L x H`, where `|T|` is the full target length, `|G|` is the number of generated tokens, `L` is the number of model layers and `H` is the number of attention heads in the model.
> 
> Indeed, the plot you attached shows the expected behavior from the attribution output: the default aggregator of the attention outputs is used under the hood by `out.show` to mean-aggregate across the last two dimensions (heads and layers, in this order), producing the `|T| x |G| ` matrix you attached. A cell in row X and column Y in this matrix represents _the aggregated attention weight assigned to the model to prefix token X when generating token Y_, where aggregated attention corresponds in this case to the mean attention weight across all layers and heads. Leter in the tutorial you can find examples of how to use `aggregate` to perform custom aggregation to extract e.g. the weight of a single head in a single layer of the model.
> 
> Finally, the reason for missing values in the target matrix is that generation is a sequential process: when a new token (column) is being generated the model can attend only to previous tokens (rows) during prediction. After the token is generated, it gets added to the prefix (i.e. becomes the next row in the matrix) and can be used by the model to predict the next token, so it will have an attention score from here onwards. This produces an upper triangular pattern like the one you see in the image.
> 
> Hope it helps! 🙂 For further questions, it would be great if you wanted to join the Inseq Discord server! You can find the invite here: https://discord.gg/V5VgwwFPbu

Hi, I have a quick question, how can we visualize the target attribution of a certain layer on a certain attention head? Is it possible the show code as an example, please?
